# Generated by Django 2.2.6 on 2019-11-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ferramenta_registrada', models.CharField(max_length=255)),
                ('id_usuario', models.IntegerField(max_length=255)),
            ],
        ),
    ]
