# Generated by Django 2.2.6 on 2019-11-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_registros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros',
            name='id_usuario',
            field=models.IntegerField(),
        ),
    ]
